#!/usr/bin/env perl
### Test that the module(s) load!(s)
use	Test::More;
BEGIN{ use_ok( Test::Pod, qw( 1.48 ) ) };
BEGIN{ use_ok( TAP::Formatter::Console ) };
BEGIN{ use_ok( TAP::Harness ) };
BEGIN{ use_ok( TAP::Parser::Aggregator ) };
BEGIN{ use_ok( version ) };
BEGIN{ use_ok( Test::Moose ) };
BEGIN{ use_ok( Data::Dumper ) };
BEGIN{ use_ok( Capture::Tiny, qw( capture_stderr capture_stdout ) ) };
BEGIN{ use_ok( Carp, qw( cluck ) ) };
BEGIN{ use_ok( Clone, qw( clone ) ) };
BEGIN{ use_ok( Type::Tiny, 1.000 ) };
BEGIN{ use_ok( Moose ) };
BEGIN{ use_ok( MooseX::StrictConstructor ) };
BEGIN{ use_ok( MooseX::HasDefaults::RO ) };
BEGIN{ use_ok( Archive::Zip ) };
BEGIN{ use_ok( File::Temp ) };
BEGIN{ use_ok( DateTimeX::Format::Excel, 0.012 ) };
BEGIN{ use_ok( MooseX::ShortCut::BuildInstance, 1.026 ) };
BEGIN{ use_ok( MooseX::ShortCut::BuildInstance, qw( build_instance ) ) };
BEGIN{ use_ok( DateTime::Format::Flexible ) };
BEGIN{ use_ok( Spreadsheet::Reader::Format ) };
use	lib '../lib', 'lib';
BEGIN{ use_ok( Spreadsheet::Reader::ExcelXML, 0.001 ) };
BEGIN{ use_ok( Spreadsheet::Reader::ExcelXML::Cell, 0.001 ) };
BEGIN{ use_ok( Spreadsheet::Reader::ExcelXML::CellToColumnRow, 0.001 ) };
BEGIN{ use_ok( Spreadsheet::Reader::ExcelXML::Chartsheet, 0.001 ) };
BEGIN{ use_ok( Spreadsheet::Reader::ExcelXML::Error, 0.001 ) };
BEGIN{ use_ok( Spreadsheet::Reader::ExcelXML::Row, 0.001 ) };
BEGIN{ use_ok( Spreadsheet::Reader::ExcelXML::SharedStrings, 0.001 ) };
BEGIN{ use_ok( Spreadsheet::Reader::ExcelXML::Styles, 0.001 ) };
BEGIN{ use_ok( Spreadsheet::Reader::ExcelXML::Types, 0.001 ) };
BEGIN{ use_ok( Spreadsheet::Reader::ExcelXML::Workbook, 0.001 ) };
BEGIN{ use_ok( Spreadsheet::Reader::ExcelXML::WorkbookFileInterface, 0.001 ) };
BEGIN{ use_ok( Spreadsheet::Reader::ExcelXML::WorkbookMetaInterface, 0.001 ) };
BEGIN{ use_ok( Spreadsheet::Reader::ExcelXML::WorkbookPropsInterface, 0.001 ) };
BEGIN{ use_ok( Spreadsheet::Reader::ExcelXML::WorkbookRelsInterface, 0.001 ) };
BEGIN{ use_ok( Spreadsheet::Reader::ExcelXML::Worksheet, 0.001 ) };
BEGIN{ use_ok( Spreadsheet::Reader::ExcelXML::WorksheetToRow, 0.001 ) };
BEGIN{ use_ok( Spreadsheet::Reader::ExcelXML::XMLReader, 0.001 ) };
BEGIN{ use_ok( Spreadsheet::Reader::ExcelXML::XMLReader::FileWorksheet, 0.001 ) };
BEGIN{ use_ok( Spreadsheet::Reader::ExcelXML::XMLReader::NamedSharedStrings, 0.001 ) };
BEGIN{ use_ok( Spreadsheet::Reader::ExcelXML::XMLReader::NamedStyles, 0.001 ) };
BEGIN{ use_ok( Spreadsheet::Reader::ExcelXML::XMLReader::NamedWorksheet, 0.001 ) };
BEGIN{ use_ok( Spreadsheet::Reader::ExcelXML::XMLReader::PositionSharedStrings, 0.001 ) };
BEGIN{ use_ok( Spreadsheet::Reader::ExcelXML::XMLReader::PositionStyles, 0.001 ) };
BEGIN{ use_ok( Spreadsheet::Reader::ExcelXML::XMLReader::WorkbookMeta, 0.001 ) };
BEGIN{ use_ok( Spreadsheet::Reader::ExcelXML::XMLReader::WorkbookProps, 0.001 ) };
BEGIN{ use_ok( Spreadsheet::Reader::ExcelXML::XMLReader::WorkbookRels, 0.001 ) };
BEGIN{ use_ok( Spreadsheet::Reader::ExcelXML::XMLReader::WorkbookXML, 0.001 ) };
BEGIN{ use_ok( Spreadsheet::Reader::ExcelXML::ZipReader, 0.001 ) };
BEGIN{ use_ok( Spreadsheet::Reader::ExcelXML::ZipReader::WorkbookMeta, 0.001 ) };
BEGIN{ use_ok( Spreadsheet::Reader::ExcelXML::ZipReader::WorkbookProps, 0.001 ) };
BEGIN{ use_ok( Spreadsheet::Reader::ExcelXML::ZipReader::WorkbookRels, 0.001 ) };
done_testing();
